CREATE OR ALTER PROCEDURE SP_FATO_VENDA_LOJA_MENSAL
AS
BEGIN
    TRUNCATE TABLE FATO_VENDA_LOJA_MENSAL;

    INSERT INTO FATO_VENDA_LOJA_MENSAL
    SELECT T.ID_TEMPO, F.ID_LOJA, SUM(F.VOLUME), SUM(F.VALOR), SUM(F.QUANTIDADE)
    FROM FATO_VENDA F
    INNER JOIN DIM_TEMPO T ON F.ID_TEMPO = T.ID_TEMPO
    GROUP BY T.ID_TEMPO, F.ID_LOJA;
END;


SELECT T.MES, T.ANO, F.ID_LOJA, 
       SUM(F.VOLUME) AS VOLUME_TOTAL, 
       SUM(F.VALOR) AS VALOR_TOTAL, 
       SUM(F.QUANTIDADE) AS QUANTIDADE_TOTAL
FROM FATO_VENDA F 
INNER JOIN DIM_TEMPO T ON F.ID_TEMPO = T.ID_TEMPO
GROUP BY T.MES, T.ANO, F.ID_LOJA;


--SELECT name FROM sys.columns WHERE object_id = OBJECT_ID('DIM_TEMPO');



