-- Tabelas de Violações

CREATE TABLE TB_VIO_VENDA (
        ID_VIOLACAO INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	DATA_CARGA DATETIME NOT NULL,
	DATA_VENDA DATETIME NULL,
	COD_LOJA INT NULL,
	COD_PRODUTO INT  NULL,
	COD_TIPO_PAGAMENTO INT NULL,
	COD_VENDA INT NULL,
	VOLUME NUMERIC(10,2) NULL,
	VALOR NUMERIC(10,2) NULL,
	DT_ERRO DATETIME NOT NULL,
        VIOLACAO VARCHAR(150) NOT NULL
)


select * from TB_VIO_VENDA