create or alter procedure sp_dim_produto2(@data_carga datetime)
as
begin
   DECLARE @COD_PRODUTO INT,
		   @PRODUTO VARCHAR(100),
		   @COD_CATEGORIA INT,
		   @CATEGORIA VARCHAR(100),
		   @CURRENT_PRODUTO VARCHAR(100),
		   @CURRENT_COD_CATEGORIA INT,
		   @CURRENT_CATEGORIA VARCHAR(100)

	DECLARE CUR CURSOR FOR
	SELECT COD_PRODUTO, PRODUTO, COD_CATEGORIA, CATEGORIA FROM TB_AUX_PRODUTO

	OPEN CUR
	FETCH CUR INTO @COD_PRODUTO, @PRODUTO, @COD_CATEGORIA, @CATEGORIA

	WHILE @@FETCH_STATUS = 0
	BEGIN
		IF (EXISTS (SELECT 1 FROM DIM_PRODUTO WHERE COD_PRODUTO = @COD_PRODUTO))
		BEGIN
			SELECT @CURRENT_PRODUTO = PRODUTO, @CURRENT_COD_CATEGORIA = COD_CATEGORIA, @CURRENT_CATEGORIA = CATEGORIA
			FROM DIM_PRODUTO
			WHERE COD_PRODUTO = @COD_PRODUTO

			IF (@CURRENT_PRODUTO != @PRODUTO OR
				@CURRENT_COD_CATEGORIA != @COD_CATEGORIA OR
				@CURRENT_CATEGORIA != @CATEGORIA)
			BEGIN
				UPDATE DIM_PRODUTO
				SET PRODUTO = @PRODUTO,
					COD_CATEGORIA = @COD_CATEGORIA,
					CATEGORIA = @CATEGORIA
				WHERE COD_PRODUTO = @COD_PRODUTO
			END
		END
		ELSE
		BEGIN
			INSERT INTO DIM_PRODUTO
			VALUES (@COD_PRODUTO, @PRODUTO, @COD_CATEGORIA, @CATEGORIA)
		END

		FETCH CUR INTO @COD_PRODUTO, @PRODUTO, @COD_CATEGORIA, @CATEGORIA
	END
	CLOSE CUR
	DEALLOCATE CUR
end
-- DUVIDA: NESSE CASO O COD_PRODUTO NAO DEVE SER ALTERADO POEQUE SERIA CONSIDERADO UM NOVO REGISTRO DE PRODTO? (VALE PARA AS OUTRAS DIMENCOES)

-- Teste

exec sp_dim_produto2 '20230321'

select * from dim_produto