create or alter procedure sp_dim_loja3(@data_carga datetime)
as
begin
	DECLARE @COD_LOJA INT,
			@LOJA VARCHAR(100),
			@CIDADE VARCHAR(100),
			@ESTADO VARCHAR(100),
			@SIGLA VARCHAR(2),
			@CURRENT_LOJA VARCHAR(100),
			@CURRENT_CIDADE VARCHAR(100),
			@CURRENT_ESTADO VARCHAR(100),
			@CURRENT_SIGLA VARCHAR(2)

	DECLARE CUR CURSOR FOR
	SELECT COD_LOJA, LOJA, CIDADE, ESTADO, SIGLA_ESTADO FROM TB_AUX_LOJA

	OPEN CUR
	FETCH CUR INTO @COD_LOJA, @LOJA, @CIDADE, @ESTADO, @SIGLA

	WHILE @@FETCH_STATUS = 0
	BEGIN
		IF(EXISTS (SELECT 1 FROM DIM_LOJA WHERE COD_LOJA = @COD_LOJA))
		BEGIN
			SELECT @CURRENT_LOJA = LOJA, @CURRENT_CIDADE = CIDADE, @CURRENT_ESTADO = ESTADO, @CURRENT_SIGLA = SIGLA_ESTADO
			FROM DIM_LOJA
			WHERE COD_LOJA = @COD_LOJA

			IF (@CURRENT_LOJA != @LOJA OR 
				@CURRENT_CIDADE != @CIDADE OR 
				@CURRENT_ESTADO != @ESTADO)
			BEGIN
				UPDATE DIM_LOJA
				SET LOJA = @LOJA,
					CIDADE = @CIDADE,
					ESTADO = @ESTADO,
					SIGLA_ESTADO = @SIGLA
				WHERE COD_LOJA = @COD_LOJA
			END
		END
		ELSE
		BEGIN
			INSERT INTO DIM_LOJA
			VALUES(@COD_LOJA, @LOJA, @CIDADE, @ESTADO, @SIGLA)
		END
		FETCH CUR INTO @COD_LOJA, @LOJA, @CIDADE, @ESTADO, @SIGLA
	END

	CLOSE CUR
	DEALLOCATE CUR
end



-- Teste

exec sp_dim_loja3 '20230321'

select * from dim_loja