create or alter procedure sp_fato_venda(@data_carga datetime)
as
begin
	DECLARE @DATA_VENDA DATETIME,
			@COD_LOJA INT,
			@COD_PRODUTO INT,
			@COD_TIPO_PGMT INT,
			@COD_VENDA INT,
			@VOLUME INT,
			@VALOR NUMERIC (10,2),
			@ID_TEMPO INT,
			@ID_LOJA INT,
			@ID_PRODUTO INT,
			@ID_TIPO_PGMT INT

	DECLARE CUR CURSOR FOR
	SELECT DATA_VENDA, COD_LOJA, COD_PRODUTO, COD_TIPO_PAGAMENTO, COD_VENDA, VOLUME, VALOR
	FROM TB_AUX_VENDA
	WHERE @data_carga = DATA_CARGA

	OPEN CUR
	FETCH CUR INTO @DATA_VENDA, @COD_LOJA, @COD_PRODUTO, @COD_TIPO_PGMT, @COD_VENDA, @VOLUME, @VALOR

	WHILE @@FETCH_STATUS = 0
	BEGIN
		
		SELECT @ID_TEMPO = ID_TEMPO 
		FROM DIM_TEMPO 
		WHERE DATA = @DATA_VENDA

		SELECT @ID_LOJA = ID_LOJA
		FROM DIM_LOJA
		WHERE COD_LOJA = @COD_LOJA

		SELECT @ID_PRODUTO = ID_PRODUTO 
		FROM DIM_PRODUTO
		WHERE COD_PRODUTO = @COD_PRODUTO

		SELECT @ID_TIPO_PGMT = ID_TIPO_PAGAMENTO
		FROM DIM_TIPO_PAGAMENTO
		WHERE COD_TIPO_PAGAMENTO = @COD_TIPO_PGMT

		IF (EXISTS (SELECT 1 FROM FATO_VENDA WHERE COD_VENDA = @COD_VENDA))
		BEGIN
			UPDATE FATO_VENDA
			SET ID_TEMPO = @ID_TEMPO,
				ID_LOJA = @ID_LOJA,
				ID_PRODUTO = @ID_PRODUTO,
				ID_TIPO_PAGAMENTO = @ID_TIPO_PGMT,
				VOLUME = @VOLUME,
				VALOR = @VALOR
			WHERE COD_VENDA = @COD_VENDA
		END
		ELSE
		BEGIN
			INSERT INTO FATO_VENDA 
			VALUES (@ID_TEMPO, @ID_LOJA, @ID_PRODUTO, @ID_TIPO_PGMT, @COD_VENDA, @VOLUME, @VALOR, 1)
		END
		
		FETCH CUR INTO @DATA_VENDA, @COD_LOJA, @COD_PRODUTO, @COD_TIPO_PGMT, @COD_VENDA, @VOLUME, @VALOR
	END

	CLOSE CUR
	DEALLOCATE CUR
end



-- Teste

exec sp_fato_venda '20230321'

TRUNCATE TABLE FATO_VENDA

select * from fato_venda
order by COD_VENDA